### ISSUE TITLE
bibliography display issues

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-eXist-app#469]
@wsalesky , I've uploaded the new bibls from Zanetti and replaced the bibl elements in works using the scripts you wrote earlier. I'll log here the display issues I see as they're visualized on the HTML pages:

- Journal titles + vols. are not showing correctly. See http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/1000#bibl1000-2. Unless @davidamichelson has told you something different, I think this should be formatted like so:
J.M. Bover, "S. Ephraem, Doctoris Syri, testimonia de Universali B. Mariae V. Mediatione," *Ephemerides theologicae lovanienses* 4 (1927), pp: 161-179.

**Comment by nathangibson** [comment]
- I've had to do some complex stuff with journals that have multiple series, and it would be nice if we could visualize these better:
 - If Zanetti references a journal volume number and also gives the series number, but there are not competing volume numbers, I've just given the series number as a biblScope, e.g., 
    `<monogr>
                  <title level="m">Oriens christianus</title>
                  <idno type="zotero">98</idno>
                  <imprint>
                     <date>1920</date>
                  </imprint>
                  <biblScope unit="series" from="2" to="2" xml:lang="de">Neue Serie</biblScope>
                  <biblScope unit="vol" from="9" to="9">9</biblScope>
                  <biblScope unit="pp" from="121" to="123">121-123</biblScope>
               </monogr>`.
I think this should appear as *Oriens christianus* 9 (1920, series 2), pp: 121-123.
- However, if there are competing volume numbering systems (one for the volume number within the series and one apart from the series), I've put the series title and vol. number inside a `<series>` tag, like so:
`<monogr>
                  <title level="j" xml:lang="fr">Revue de l'Orient chrétien</title>
                  <idno type="zotero">118</idno>
                  <imprint>
                     <date>1914</date>
                  </imprint>
                  <biblScope unit="vol" from="19" to="19">19</biblScope>
                  <biblScope unit="pp" from="103" to="105">103-105</biblScope>
               </monogr>
               <series>
                  <title level="s" xml:lang="fr">Revue de l'Orient chrétien</title>
                  <biblScope unit="series" from="2" to="2" xml:lang="fr">Deuxieme Série</biblScope>
                  <biblScope unit="vol" from="9" to="9">9</biblScope>
               </series>`
My opinion is that this should appear as *Revue de l'Orient chrétien* 19 (1914) (=*Revue de l'Orient chrétien*, series 2, vol. 9), pp: 103-105. But we should get @davidamichelson 's input before finalizing.

**Comment by nathangibson** [comment]
@davidamichelson What style guide are we following?

**Comment by nathangibson** [comment]
- Articles inside titled volumes of multi-volume books need some help. E.g., http://wwwb.library.vanderbilt.edu/work/297#bibl297-71, which is citing http://wwwb.library.vanderbilt.edu/bibl/991.
The code is too long to reproduce here, but I think the visualization should be something like
G. Bornkamm, "Thomasakten," in E. Hennecke et al. (eds.), *Neutestamentliche Apokryphen in deutscher Übersetzung*, vol. 2, *Apostolisches, Apokalypsen und Verwandtes* (Tübingen: n.p., 1964), pp: 349-353.
- Related to this, when there are multiple `monogr` elements, only the first one should have publication info visualized (rather than both, as is happening now).

**Comment by nathangibson** [comment]
I've implemented some `<relatedItem>` usage for translations and reprints (e.g., bibl/997), but we'll need to discuss with @davidamichelson  how this info should be visualized. (Typically, this is where Zanetti used an "=".)

**Comment by nathangibson** [comment]
- Some articles span multiple volumes--e.g., bibl/1050, cited in http://wwwb.library.vanderbilt.edu/work/1715#bibl1715-2. Ideally, this would be visualized as 
J.-M. Fiey, "Isho‘yaw le Grand. Vie du Catholicos nestorien Isho‘yaw III d’Adiabène (580-659)," *Orientalia christiana periodica* 35 (1969), pp: 305-333; 36 (1970), p. 5-46. However, I'm not sure how show which citedRange pages go with which volume, using tei:biblStruct, nor has the TEI listserv helped me on this. Any suggestions on how to encode this?

**Comment by wsalesky** [comment]
@nathangibson Thanks, I will take a look. For reference here is an earlier issue created by @tacarlson: #362 The issue is closed, but I see a lot of the same formatting issues that were reported in #362 are still a problem.

**Comment by nathangibson** [comment]
Thanks!

**Comment by nathangibson** [comment]
Should I merge these issues?

**Comment by wsalesky** [comment]
Sure.

**Comment by nathangibson** [comment]
Oh, sorry, not figuring out how to do that.

**Comment by wsalesky** [comment]
Hum, does not look like you can. Referencing the issue in this issue should be fine. It will link them, and should notify anyone on the other issue of new changes.

**Comment by nathangibson** [comment]
OK, thanks.

**Comment by nathangibson** [comment]
- There are several items that use non-Latin scripts for authors and titles. I've included Latin script alternatives for these. 
 - E.g., http://wwwb.library.vanderbilt.edu/work/345#bibl345-2, which cites bibl/902:
`            <biblStruct corresp="bibl345-2">
               <analytic>
                  <author>
                     <persName xml:lang="ru-Latn-iso9r95">
                        <forename>E.</forename>
                        <surname>Aničkov</surname>
                     </persName>
                     <persName xml:lang="ru">
                        <forename>Е.</forename>
                        <surname>Аничков</surname>
                     </persName>
                  </author>
                  <title level="a" xml:lang="ru-Latn-iso9r95">Sv. Nikolaj i Artemida Èfesskaâ</title>
                  <title level="a" xml:lang="ru">Св. Николай и Артемида Эфесская</title>
                  <idno type="URI">http://syriaca.org/bibl/902</idno>
                  <idno type="URI">http://krotov.info/acts/10/3/nikolay.htm</idno>
               </analytic>
               <monogr>
                  <title level="j" xml:lang="ru-Latn-iso9r95">Zapiski Vostočnogo otdeleniâ
                     Imperatorskogo Russkogo Arheologičeskogo obŝestva</title>
                  <title level="j" xml:lang="ru">Записки Восточного отделения Императорского
                     Русского Археологического общества</title>
                  <imprint>
                     <date>1895</date>
                  </imprint>
                  <biblScope unit="vol" from="9" to="9">9</biblScope>
                  <biblScope unit="pp" from="69" to="77">69-77</biblScope>
               </monogr>
               <citedRange from="69" to="77" unit="pp" corresp="bibl345-2">69-77</citedRange>
            </biblStruct>`
 - As you can see, I'm giving alternate `persName`s inside author, as well as alternate `title`s, all labeled with different language codes. So the stylesheet should be able to pick one language and use just that one. It looks like it is correctly picking only one author/persName and one monogr/title, but is trying to spit out both analytic/titles. I think we'll prefer to show the original language script ("ru", "ar", "syr", "el") rather than the transliteration. (Eventually, this might be a user setting???)

**Comment by nathangibson** [comment]
- Can we render all `<note>` elements inside `<citedRange>` inside parentheses? E.g., http://wwwb.library.vanderbilt.edu/work/980#bibl980-6 should have "pp: 286-289 **(**dans note**)**"
- Can we separate multiple citedRange/@unit="pp" with just a comma, instead of repeating "pp: "? E.g., http://wwwb.library.vanderbilt.edu/work/980#bibl980-6 should be "pp: 286-289 (dans note), 340."

**Comment by nathangibson** [comment]
Another example of titled volumes is http://wwwb.library.vanderbilt.edu/work/980#bibl980-6, which is only rendering one of the monogr/titles and is duplicating the author name. This should be 
J.S. Assemani, *Bibliotheca orientalis Clementino-Vaticana*, vol. 1, *De scriptoribus Syris Nestorianis* (Rome: n.p., 1725)...

**Comment by nathangibson** [comment]
- It looks to me like `<series>` info is not rendering at all. 
 - E.g., http://wwwb.library.vanderbilt.edu/work/895#bibl895-10. Since Thomas said we're following a modified Chicago style, I suppose this would be visualized as 
W. Hage, *Syriac Christianity in India*, Mōrān ‘Eth’ō Series, 1 (Kottayam: n.p., 1988).
 - A more complicated example is http://wwwb.library.vanderbilt.edu/work/293#bibl293-2 (bibl/1000), which should be visualized S. Gero, *Barṣauma of Nisibis and Persian Christianity in the Fifth Century*, Corpus Scriptorum Christianorum Orientalium, 37; Corpus Scriptorum Christianorum Orientalium, Subsidia, 63 (Louvain: n.p., 1981), pp: 97-109.

**Comment by nathangibson** [comment]
- I've used `<note type="flag">` for internal comments about stuff we should check. Would you mind suppressing the visualization of these notes?

**Comment by nathangibson** [comment]
OK, that's it for now. Thanks for all your hard work, and let me know if you have questions.

**Comment by wsalesky** [comment]
@nathangibson Awesome thanks for the list. I will let you know as changes get made. I think there is some conflicting code in the citation stylesheets, so this may take a few days to get everything ironed out.

**Comment by nathangibson** [comment]
Great. It's also possible that I've made some encoding decisions that conflict with our previous ones. If you come across anything like that, let me know and we'll try to figure out how to resolve them.

**Comment by wsalesky** [comment]
@nathangibson First pass is up on dev. Will need to discuss a few issues before I make more progress. Thanks for all your work putting together the list.

**Comment by nathangibson** [comment]
Thanks @wsalesky ! Yes, it's an improvement. Perhaps one of the issues you're referring to: journal articles are still showing with "n.p., " in front of the date for "no publisher" -- that can just be removed (for journal articles only)

**Comment by wsalesky** [comment]
@nathangibson I think I caught all the issues we discussed. My notes from the meeting could have been better. Let me know if you find anything I missed, or anything new. 
Thanks.

**Comment by nathangibson** [comment]
OK, I’ll take a look.

**Comment by wsalesky** [comment]
@nathangibson Have I managed to resolve all of these? I think so. If yes, you can close the ticket.

**Comment by nathangibson** [comment]
@wsalesky No, unfortunately there are still issues. Sorry to be slow getting back to you. Some I may have missed earlier. Some examples:

- items with multiple scripts
 - use native script for author, not just title (http://wwwb.library.vanderbilt.edu/work/930):
   - A.V. Pajkova, "К вопросу о возникновении беллетристического повествования в сирийской литературе," Палестинский сборник vol. 23 (86) (1971), pp: 173-178.
    - should be: Аза Владимировна Пайкова, "К вопросу о возникновении беллетристического повествования в сирийской литературе," Палестинский сборник vol. 23 (86) (1971), pp: 173-178.
 - both latin and arabic titles showing up for http://wwwb.library.vanderbilt.edu/work/250#bib250-13, though I'm honestly not sure how the bidirectional text would be best visualized here.
- monogrs need space between title and pub info (http://wwwb.library.vanderbilt.edu/work/250#bib250-9):
 - M. Huber. *Die Wanderlegende von den Siebenschläfern. Eine literargeschichtliche Untersuchung*(Leipzig, 1910)
 - should be: M. Huber. *Die Wanderlegende von den Siebenschläfern. Eine literargeschichtliche Untersuchung* (Leipzig, 1910)
- monogr in series (http://wwwb.library.vanderbilt.edu/work/270): 
 - P. Devos, "Les Martyrs persans à travers leurs Actes syriaques," in *Atti del Convegno sul tema: La Persia e il mondo greco-romano (Roma 11-14 aprile 1965)*(Rome, 1966) (Problemi attuali di scienza e di cultura, vol. 76), pp: 213-225.
 - should be: P. Devos, "Les Martyrs persans à travers leurs Actes syriaques," in *Atti del Convegno sul tema: La Persia e il mondo greco-romano (Roma 11-14 aprile 1965)* (Problemi attuali di scienza e di cultura, vol. 76; Rome, 1966), pp: 213-225. [space after monogr title, series info and pub info both in same parentheses set, in that order, followed by semicolon]
- monogr volume of multivolume monogr set (http://wwwb.library.vanderbilt.edu/work/270):
 - J.S. Assemani. *De scriptoribus Syris Nestorianis*(Rome, 1725), *Bibliotheca orientalis Clementino-Vaticana* vol. 1 (1719-1728), pp: 12-13, pp: 186-187.
 - should be: J.S. Assemani. *De scriptoribus Syris Nestorianis*, *Bibliotheca orientalis Clementino-Vaticana* vol. 1 (Rome, 1725), pp: 12-13, 186-187. [use only pub info for *volume* and place at end (pub info for set required by TEI but doesn't need to be displayed), use only a comma to separate citedRanges with same type (don't repeat "pp.")]

That's all I see for now. I can take another look after you fix those. Thanks so much!

**Comment by wsalesky** [comment]
I think we need to standardize how we are indicating titles that have been transliterated. See some of the differences in these two examples:

http://wwwb.library.vanderbilt.edu/bibl/1039/tei
(Transliteration indicated by xml:lang=''en-x-gedsh")

and
http://wwwb.library.vanderbilt.edu/bibl/738/tei
(Transliteration indicated by xml:lang="ru-Latn-iso9r95")

Can we either standardize the xml:lang attributes for transliterations, or perhaps there is an additional attribute that can indicate either transliterated format, or indicate "primary" format?

Thoughts? I can code the xslt to include all the variations on xml:lang attribute, but I think that would be a messy, harder to maintain solution.

**Comment by nathangibson** [comment]
Yes, I agree. Actually, I think we could probably just remove the transliterations of titles which we are planning to display in their original script. Thoughts, @davidamichelson ?

I think "en-x-gedsh" is the primary problem. It kind-of makes sense for names, which have a mixture of English and Syriac transliteration (e.g., "Pawla of Edessa"). But if something is purely a transliteration, perhaps we should use ar-Latn-gedsh or syr-Latn-gedsh, etc.?

**Comment by wsalesky** [comment]
Okay, I think I have caught all of these. We will still need to discuss xml:lang normalization.

**Comment by nathangibson** [comment]
@davidamichelson @dlschwartz 
So, I remember we decided not to transliterate bibliographic entries for Russian, Greek, Armenian, etc. -- just to display these in their original scripts. 

**However**, did we for sure decide not to provide transliterations for Syriac and Arabic bibliographic info, in addition to the original script? I want to check before removing these transliterations, which are currently messing up the display of citations (e.g., http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bibl/646). The advantage of having both transliterated and original scripts is that people will be able to find them easier in search and browse. The disadvantage is that we have to code when to use which script.

**Comment by wsalesky** [comment]
We can choose a title to use, there are currently no rules for handling multiple scripts. 
Related to this issue as well I think: #569

**Comment by nathangibson** [comment]
Not sure if this is the right place to put this. There are issues with visualization of bibliography Editions/Translations/Ancient Versions. E.g., http://syriaca.org/work/396 edition 1:
> Bedjan, P.AMS 6vol: 6, : p. 465-499. 

1. Spaces are not showing up between elements (author, title, etc.) 
2. Info doesn't seem to be grabbed from the bibl record indicated in the ptr (e.g., title is abbreviation instead of full title here http://syriaca.org/bibl/1697).
3. Link icons to works cited module and external cites don't display. Instead entire item is visualized as a link.

Perhaps this is related to stylesheet changes made for #724 ?

**Comment by nathangibson** [comment]
Re. bibls inside notes:
NSHL suggested schema does not put editions, translations, etc. inside notes as BHSE does. We could convert BHSE to this format. An example of the NHSL format is http://wwwb.library.vanderbilt.edu/work/2501. 

For reference, an example of a bibl inside a prose note (e.g., abstract) that should *not* be visualized as a full citation is http://wwwb.library.vanderbilt.edu/person/2171, which however points to a work entity.

**Comment by nathangibson** [comment]
Another example of bibl inside abstract is wwwb.library.vanderbilt.edu/person/2211.
Example of bibl inside note for editions/translations/ancient versions is any BHSE record.

**Comment by wsalesky** [comment]
@nathangibson Please take a look now:
http://wwwb.library.vanderbilt.edu/work/270

I will do some spot checking to make sure I haven't messed up any other display and if you could do so as well that would be helpful. 
Thanks!

**Comment by nathangibson** [comment]
Thanks this is looking great now!

**Comment by wsalesky** [comment]
Okay. I will push the changes to the production server. Thanks.

**Comment by wsalesky** [comment]
Updated.
